// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firedart/firedart.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCintY7HqBq0WwJ-jHESZoyyLScwZ4LtQY',
    appId: '1:324691481952:web:02452e239d36676f957a05',
    messagingSenderId: '324691481952',
    projectId: 'amigo-support',
    authDomain: 'amigo-support.firebaseapp.com',
    databaseURL:
        'https://amigo-support-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amigo-support.appspot.com',
    measurementId: 'G-5CQ7BWD7FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmfylVBj7BPBqOcrK9FRvjy5hDCA3Sbho',
    appId: '1:324691481952:android:9e44fcff301291ec957a05',
    messagingSenderId: '324691481952',
    projectId: 'amigo-support',
    databaseURL:
        'https://amigo-support-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amigo-support.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnA1k_4zzZPTDKyH-vkIoOgYKfNSkUucM',
    appId: '1:324691481952:ios:19e834598a18eb47957a05',
    messagingSenderId: '324691481952',
    projectId: 'amigo-support',
    databaseURL:
        'https://amigo-support-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amigo-support.appspot.com',
    iosClientId:
        '324691481952-mvcljs5m3lblmelsdfq95rh2tu55v7p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.amigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnA1k_4zzZPTDKyH-vkIoOgYKfNSkUucM',
    appId: '1:324691481952:ios:19e834598a18eb47957a05',
    messagingSenderId: '324691481952',
    projectId: 'amigo-support',
    databaseURL:
        'https://amigo-support-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amigo-support.appspot.com',
    iosClientId:
        '324691481952-mvcljs5m3lblmelsdfq95rh2tu55v7p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.amigo',
  );
}
